version: "3.8"
services:
  mysql:
    container_name: RnDProject
    image: mysql/mysql-server:8.0.23
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 3DScannerApplication
      MYSQL_ROOT_HOST: "%"
    command: --lower_case_table_names=1
    volumes:
      - ./dbdata:/var/lib/mysql